universe = vanilla

executable = run_all_preVFP.sh

outputfile = Muon_$(sample)_2016_preVFP_$(Cluster)_$(Process).root

arguments = $(sample) $(inputfile) $(macro) $(outputfile)

should_transfer_files = YES
when_to_transfer_output = ON_EXIT
transfer_executable = YES

transfer_input_files = \
    Muon_MC_200_2016_preVFP.cc, \
    Muon_MC_500_2016_preVFP.cc, \
    Muon_MC_1000_2016_preVFP.cc, \
    Muon_MC_2000_2016_preVFP.cc, \
    Muon_WToTauNu_M_200_2016_preVFP.cc, \
    Muon_WToTauNu_M_500_2016_preVFP.cc, \
    Muon_WToTauNu_M_1000_2016_preVFP.cc, \
    Muon_WToTauNu_M_2000_2016_preVFP.cc, \
    Muon_TTTo2L2Nu_2016_preVFP.cc, \
    Muon_TTToSemiLeptonic_2016_preVFP.cc, \
    Muon_ST_s_channel_4f_leptonDecays_2016_preVFP.cc, \
    Muon_ST_t_channel_antitop_4f_InclusiveDecays_2016_preVFP.cc, \
    Muon_ST_t_channel_top_4f_InclusiveDecays_2016_preVFP.cc, \
    Muon_ST_tW_antitop_5f_inclusiveDecays_2016_preVFP.cc, \
    Muon_ST_tW_top_5f_inclusiveDecays_2016_preVFP.cc, \
    Muon_WWTo1L1Nu2Q_2016_preVFP.cc, \
    Muon_WWTo2L2Nu_2016_preVFP.cc, \
    Muon_WWTo4Q_4f_2016_preVFP.cc, \
    Muon_WZTo1L1Nu2Q_4f_2016_preVFP.cc, \
    Muon_WZTo1L3Nu_4f_2016_preVFP.cc, \
    Muon_WZTo2Q2Nu_4f_2016_preVFP.cc, \
    Muon_WZTo3LNu_2016_preVFP.cc, \
    Muon_ZZ_2016_preVFP.cc, \
    eff_mu_ID.root, \
    eff_mu_ISO.root, \
    eff_mu_STRIG.root, \
    PUreweight.root

transfer_output_files = $(outputfile)

output = logs/all_$(sample)_$(Cluster)_$(Process).out
error  = logs/all_$(sample)_$(Cluster)_$(Process).err
log    = logs/all_$(sample)_$(Cluster)_$(Process).log

request_cpus   = 1
request_memory = 6000MB
request_disk   = 5000MB

queue sample, inputfile, macro from all_inputs_preVFP.txt