universe = vanilla

executable = run_Muon_fake_rate.sh

arguments = $(inputfile) fake_mu_$(Cluster)_$(Process).root

output = logs/real_rate_$(Cluster)_$(Process).out
error  = logs/real_rate_$(Cluster)_$(Process).err
log    = logs/real_rate_$(Cluster)_$(Process).log

should_transfer_files = YES
when_to_transfer_output = ON_EXIT
transfer_executable = YES

transfer_input_files = Muon_fake_rate.cc

request_cpus = 1
request_memory = 2000MB
request_disk = 2000MB

queue inputfile from input_SingleMuon_2016_preVFP.txt