universe = vanilla

executable = run_Muon_QCD_2016_preVFP.sh

outputfile = Muon_QCD_2016_preVFP_$(Cluster)_$(Process).root

arguments = $(inputfile) $(outputfile)

should_transfer_files = YES
when_to_transfer_output = ON_EXIT
transfer_executable = YES

transfer_input_files = \
    Muon_QCD_2016_preVFP.cc, \
    real_mu_rate.root, \
    fake_mu_normalized_results.root

transfer_output_files = $(outputfile)

output = logs/QCD_$(Cluster)_$(Process).out
error = logs/QCD_$(Cluster)_$(Process).err
log = logs/QCD_$(Cluster)_$(Process).log

request_cpus = 1
request_memory = 2500MB
request_disk = 3GB

queue inputfile from input_SingleMuon_2016_preVFP.txt