# Submit from the ChargedDY directory: condor_submit submit_acc_eff_M1000.sub
universe = vanilla
executable = run_acc_eff.sh
arguments = 1000 $(filename) $(Cluster) $(Process)

should_transfer_files = YES
when_to_transfer_output = ON_EXIT
transfer_executable = YES
transfer_input_files = acc_eff_M1000.cc, eff_mu_ID.root, eff_mu_ISO.root, eff_mu_STRIG.root, PUreweight.root
transfer_output_files = acc_eff_M1000_$(Cluster)_$(Process).root

output = logs/acc_eff_M1000_$(Cluster)_$(Process).out
error = logs/acc_eff_M1000_$(Cluster)_$(Process).err
log = logs/acc_eff_M1000_$(Cluster)_$(Process).log

request_cpus = 1
request_memory = 6000MB
request_disk = 5000MB

queue filename from input_WToMuNu_M-1000_2016_preVFP.txt
